[DRAFT] Workspace support for 2.x
TYPO3-Headless/headless pull request #466
Opened 2022-07-28 08:41 UTC by kitzberger

2022-07-28 10:41 UTC, tmotyl commented
related: https://github.com/TYPO3-Headless/headless/pull/468

2022-08-02 12:34 UTC, twoldanski approved these changes

2022-08-02 12:35 UTC, twoldanski commented on Classes/Hooks/PreviewUrlHook.php
> +    public function postProcess(string $previewUrl, int $pageUid, array $rootLine = null, string $anchorSection, string $viewScript, string $additionalGetVars, bool $switchFocus): string
please define ?array

2022-08-02 12:36 UTC, twoldanski requested changes
Please change from `array` to `?array` in postProcess

2022-08-02 13:32 UTC, lukaszuznanski approved these changes

2022-08-02 22:32 UTC, merged