elementBodyResponse in combination with doNotGroupByColPos = 1
TYPO3-Headless/headless pull request #524
Opened 2022-12-04 14:01 UTC by MohsinQK

Fixed the possibility to get elementBodyResponse also if doNotGroupByColPos = 1 is set on lib.content

2022-12-05 09:45 UTC, twoldanski requested changes

2022-12-05 09:45 UTC, twoldanski commented on Classes/Middleware/ElementBodyResponseMiddleware.php
> +            if ((int)($item['id'] ?? 0) === $elementId) {
I think we can add this condition in first iteration in content to check if we have flat array

2022-12-05 09:45 UTC, twoldanski commented on Classes/Middleware/ElementBodyResponseMiddleware.php
> +            if ((int)($item['id'] ?? 0) === $elementId) {
and then we can skip whole additional iterations

2022-12-05 13:10 UTC, twoldanski commented on Classes/Middleware/ElementBodyResponseMiddleware.php
> +            if(isset($items['id'])) {
here you can just in use (int)($items['id'] ?? 0) === $elementId if true, array is flat & match id, then return $items, else search in nested colPos, just then condition should be after is_array check, then you can drop whole extra foreach after main one

2022-12-13 09:01 UTC, twoldanski approved these changes

2022-12-13 09:02 UTC, twoldanski requested changes

2022-12-13 09:02 UTC, twoldanski commented on Classes/Middleware/ElementBodyResponseMiddleware.php
> +            // if array is flat means doNotGroupByColPos = 1 is set
this check should be after is_array

2023-01-26 10:20 UTC, lukaszuznanski approved these changes

2023-01-26 10:20 UTC, twoldanski approved these changes

2023-01-26 10:20 UTC, merged