[BUGFIX] Get correct page id for a shortcut
TYPO3-Headless/headless pull request #672
Opened 2023-11-12 18:52 UTC by KrohnMi

When creating a shortcut in TYPO3 that points to a different root page, an incorrect link is generated.

I hope I have fixed it correctly.

2023-11-13 10:37 UTC, lukaszuznanski requested changes
Could you cover this with tests? 
By the way: is this really an issue? I mean, it's OK to have id of shortcut page, as it's redirected by 307 HTTP to other page, or I don't understand your issue.

2023-11-13 10:37 UTC, lukaszuznanski commented on Classes/Event/Listener/AfterLinkIsGeneratedListener.php
> +        if ($page != null && $page['doktype'] == PageRepository::DOKTYPE_SHORTCUT) {
I would love to have more strict comparision here

2023-11-13 12:26 UTC, KrohnMi commented
@lukaszuznanski 

My use case involves two Typo3 root pages, let's call them Page A and Page B.

On Page A, i'm building a menu using the Menubuilder, and within this menu, i have links to Page B. In the Typo3 site config, i have defined the frontend URL as a.site.com and the backend URL as api.a.site.com. Similarly, Page B has frontend URL b.site.com and backend URL api.b.site.com.

When you build the menu, the links are generated as a.site.com instead of the expected b.site.com. This is happening because the Site Configuration of Page A is being used to get the frontend url, and Page B's Site Configuration is not being used as expected.

2023-11-14 09:35 UTC, twoldanski commented
Hi @KrohnMi thanks for PR, but can you please test you issue with this PR https://github.com/TYPO3-Headless/headless/pull/675 (should solve you issue as well)

2023-11-14 11:14 UTC, lukaszuznanski commented
@KrohnMi please check if https://github.com/TYPO3-Headless/headless/pull/675 fixes your issue

2023-11-14 12:40 UTC, KrohnMi commented
@twoldanski No, unfortunately, your merge request could not resolve my issue.

2023-11-20 11:44 UTC, twoldanski commented
Hi @KrohnMi could you provide example typoscript to reproduce your issue?

2024-05-09 13:22 UTC, lukaszuznanski commented
@KrohnMi please provide some examples so we can reproduce this issue

2024-10-24 09:51 UTC, closed without merging